### ISSUE TITLE
--hide-cursor not work on Hyprland

### ISSUE THREAD

**Issue by Sokiroso** [Jappie3/wayfreeze#11] opened 2024-10-15 12:08 UTC
Using `--hide-cursor` option does not hide the cursor

- Arch Linux
- Hyprland v0.44.1 from pacman
- Wayfreeze 0.1.0 from source

[wayfreeze_hideCursor.webm](https://github.com/user-attachments/assets/cc00a47c-aaf9-4ec1-9ae1-8c836fdb843c)

**Comment by Jappie3** [comment] 2024-10-15 12:25
I was about to comment "can't reproduce (using `wayfreeze --hide-cursor --after-freeze-cmd 'grim -g "$(slurp)" - | wl-copy; killall wayfreeze'`)"

then I went to record a video, and while using wf-recorder, my cursor still showed up... weird

running hyprland 0.44.0 atm, I'll try updating once I get home

**Comment by Jappie3** [comment] 2024-10-16 15:13
can't repro on latest Hyprland

do you have hardware cursors disabled by any change? (so `no_hardware_cursors = true` in your config)

I think that `--hide-cursor` doesn't work without hardware cursors sadly...

**Comment by Sokiroso** [comment] 2024-10-18 18:30
In my hyprland configuration `no_hardware_cursors = false`. I tried using wayfreeze on a clean system and `--hide-cursor` works. Probably something in the system overrides the cursor behavior, I can't assume

**Comment by Jappie3** [comment] 2024-10-18 18:58
closing for now, feel free to re-open if your findings lead you to suspect wayfreeze ^^

**Closed by Jappie3** 2024-10-18 18:58 UTC
